-- ============================================================================
-- 酒店搜索引擎 - 采集与调度相关表结构（PostgreSQL）
-- 说明：
-- - 覆盖“动态定时任务与开关”“运行状态断点”“同步日志与失败明细”
-- - 新增“API 请求日志（压缩JSON存储）”
-- - 调整 hotels_staging 增加名称字段
-- - 全部包含索引与中文注释
-- - 建议使用 UTF-8 编码执行
-- ============================================================================

-- 为避免重复执行报错，均使用 IF NOT EXISTS/DO 块保护

-- 压缩编码枚举类型
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'compression_codec') THEN
        CREATE TYPE compression_codec AS ENUM ('none', 'gzip', 'zstd', 'lz4');
    END IF;
END$$;



-- 建表脚本


-- ----------------------------
-- Table structure for api_request_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."api_request_log";
CREATE TABLE "public"."api_request_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "trace_id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "http_method" varchar(8) COLLATE "pg_catalog"."default" NOT NULL,
  "url" text COLLATE "pg_catalog"."default" NOT NULL,
  "request_headers" jsonb NOT NULL,
  "response_status" int4,
  "duration_ms" int4,
  "request_body_compressed" bytea,
  "response_body_compressed" bytea,
  "request_size_bytes" int4,
  "response_size_bytes" int4,
  "compression" "public"."compression_codec" NOT NULL DEFAULT 'gzip'::compression_codec,
  "app" varchar(64) COLLATE "pg_catalog"."default",
  "timestamp_utc" timestamptz(6) NOT NULL DEFAULT now(),
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
)
;
ALTER TABLE "public"."api_request_log" OWNER TO "postgres";
COMMENT ON COLUMN "public"."api_request_log"."id" IS '自增主键';
COMMENT ON COLUMN "public"."api_request_log"."trace_id" IS '与同步日志相关联的追踪ID';
COMMENT ON COLUMN "public"."api_request_log"."job_code" IS '任务编码（对应 job_schedule.job_code）';
COMMENT ON COLUMN "public"."api_request_log"."source" IS '来源标识（CN/INTL 等）';
COMMENT ON COLUMN "public"."api_request_log"."http_method" IS 'HTTP 方法（GET/POST 等）';
COMMENT ON COLUMN "public"."api_request_log"."url" IS '请求URL';
COMMENT ON COLUMN "public"."api_request_log"."request_headers" IS '请求头（JSON）';
COMMENT ON COLUMN "public"."api_request_log"."response_status" IS '响应状态码';
COMMENT ON COLUMN "public"."api_request_log"."duration_ms" IS '请求耗时（毫秒）';
COMMENT ON COLUMN "public"."api_request_log"."request_body_compressed" IS '压缩后的请求体字节';
COMMENT ON COLUMN "public"."api_request_log"."response_body_compressed" IS '压缩后的响应体字节';
COMMENT ON COLUMN "public"."api_request_log"."request_size_bytes" IS '请求体大小（字节）';
COMMENT ON COLUMN "public"."api_request_log"."response_size_bytes" IS '响应体大小（字节）';
COMMENT ON COLUMN "public"."api_request_log"."compression" IS '压缩算法：none/gzip/zstd/lz4，由应用层负责压缩与解压';
COMMENT ON COLUMN "public"."api_request_log"."app" IS '供应商应用标识';
COMMENT ON COLUMN "public"."api_request_log"."timestamp_utc" IS '请求发生时间（UTC）';
COMMENT ON COLUMN "public"."api_request_log"."created_at" IS '记录创建时间';
COMMENT ON TABLE "public"."api_request_log" IS '外部API请求日志（请求/响应原文采用压缩字节存储）';

-- ----------------------------
-- Table structure for hotels
-- ----------------------------
DROP TABLE IF EXISTS "public"."hotels";
CREATE TABLE "public"."hotels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "tag_source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "hotel_id" int8 NOT NULL,
  "hotel_name_cn" text COLLATE "pg_catalog"."default",
  "hotel_name_en" text COLLATE "pg_catalog"."default",
  "new_hotel_name_cn" text COLLATE "pg_catalog"."default",
  "new_hotel_name_en" text COLLATE "pg_catalog"."default",
  "country_cn" varchar(100) COLLATE "pg_catalog"."default",
  "country_en" varchar(100) COLLATE "pg_catalog"."default",
  "country_code" varchar(10) COLLATE "pg_catalog"."default",
  "city_cn" varchar(100) COLLATE "pg_catalog"."default",
  "city_en" varchar(100) COLLATE "pg_catalog"."default",
  "region_cn" varchar(100) COLLATE "pg_catalog"."default",
  "region_en" varchar(100) COLLATE "pg_catalog"."default",
  "continent_cn" varchar(50) COLLATE "pg_catalog"."default",
  "continent_en" varchar(50) COLLATE "pg_catalog"."default",
  "address_cn" text COLLATE "pg_catalog"."default",
  "address_en" text COLLATE "pg_catalog"."default",
  "longitude" numeric(10,7),
  "latitude" numeric(10,7),
  "hotel_group_cn" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_group_en" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_brand_cn" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_brand_en" varchar(200) COLLATE "pg_catalog"."default",
  "fetched_at" timestamptz(6) DEFAULT CURRENT_TIMESTAMP,
  "description_cn" text COLLATE "pg_catalog"."default",
  "description_en" text COLLATE "pg_catalog"."default",
  "raw_compressed" text COLLATE "pg_catalog"."default" DEFAULT ''::text,
  "updated_at" timestamptz(6) DEFAULT CURRENT_TIMESTAMP
)
;
ALTER TABLE "public"."hotels" OWNER TO "postgres";
COMMENT ON COLUMN "public"."hotels"."id" IS '主键ID（自增）';
COMMENT ON COLUMN "public"."hotels"."source" IS '数据源：Elong=艺龙；Agoda=安可达';
COMMENT ON COLUMN "public"."hotels"."tag_source" IS '标签源：CN=国内；INTL=国际；GAT=港澳台';
COMMENT ON COLUMN "public"."hotels"."hotel_id" IS '酒店ID（供应商体系内的酒店标识）';
COMMENT ON COLUMN "public"."hotels"."hotel_name_cn" IS '酒店中文名（从原文解析或翻译得到）';
COMMENT ON COLUMN "public"."hotels"."hotel_name_en" IS '酒店英文名（从原文解析）';
COMMENT ON COLUMN "public"."hotels"."new_hotel_name_cn" IS '新中文名（数据源返回的标准化名称或内部清洗后的结果）';
COMMENT ON COLUMN "public"."hotels"."new_hotel_name_en" IS '新英文名（数据源返回的标准化名称或内部清洗后的结果）';
COMMENT ON COLUMN "public"."hotels"."country_cn" IS '国家中文名';
COMMENT ON COLUMN "public"."hotels"."country_en" IS '国家英文名';
COMMENT ON COLUMN "public"."hotels"."country_code" IS '国家代码（ISO 3166-1 alpha-2，如 CN/HK/MO/TW/US 等）';
COMMENT ON COLUMN "public"."hotels"."city_cn" IS '城市中文名';
COMMENT ON COLUMN "public"."hotels"."city_en" IS '城市英文名';
COMMENT ON COLUMN "public"."hotels"."region_cn" IS '区域/区县中文名';
COMMENT ON COLUMN "public"."hotels"."region_en" IS '区域/区县英文名';
COMMENT ON COLUMN "public"."hotels"."continent_cn" IS '洲中文名（如：亚洲、欧洲、北美洲等）';
COMMENT ON COLUMN "public"."hotels"."continent_en" IS '洲英文名（如：Asia、Europe、North America 等）';
COMMENT ON COLUMN "public"."hotels"."address_cn" IS '酒店地址中文原文';
COMMENT ON COLUMN "public"."hotels"."address_en" IS '酒店地址英文原文';
COMMENT ON COLUMN "public"."hotels"."longitude" IS '经度（-180 ~ 180）';
COMMENT ON COLUMN "public"."hotels"."latitude" IS '纬度（-90 ~ 90）';
COMMENT ON COLUMN "public"."hotels"."hotel_group_cn" IS '酒店集团中文名（如：万豪、希尔顿等）';
COMMENT ON COLUMN "public"."hotels"."hotel_group_en" IS '酒店集团英文名（如：Marriott、Hilton 等）';
COMMENT ON COLUMN "public"."hotels"."hotel_brand_cn" IS '酒店品牌中文名（如：JW万豪、康莱德等）';
COMMENT ON COLUMN "public"."hotels"."hotel_brand_en" IS '酒店品牌英文名（如：JW Marriott、Conrad 等）';
COMMENT ON COLUMN "public"."hotels"."fetched_at" IS '数据抓取时间（入库时间戳）';
COMMENT ON COLUMN "public"."hotels"."description_cn" IS '酒店描述（中文）';
COMMENT ON COLUMN "public"."hotels"."description_en" IS '酒店描述（英文）';
COMMENT ON COLUMN "public"."hotels"."raw_compressed" IS '酒店原文（GIZP 压缩）';
COMMENT ON COLUMN "public"."hotels"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."hotels" IS '酒店详情 Staging 表：存放采集到的酒店原文与基础解析字段';

-- ----------------------------
-- Table structure for job_runtime_state
-- ----------------------------
DROP TABLE IF EXISTS "public"."job_runtime_state";
CREATE TABLE "public"."job_runtime_state" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "watermark_max_hotel_id" int8 NOT NULL DEFAULT 0,
  "last_started_at" timestamptz(6),
  "last_finished_at" timestamptz(6),
  "last_status" varchar(20) COLLATE "pg_catalog"."default",
  "updated_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."job_runtime_state" OWNER TO "postgres";
COMMENT ON COLUMN "public"."job_runtime_state"."id" IS '自增主键';
COMMENT ON COLUMN "public"."job_runtime_state"."job_code" IS '任务编码';
COMMENT ON COLUMN "public"."job_runtime_state"."watermark_max_hotel_id" IS '基于供应商API的 maxHotelId 断点续跑水位';
COMMENT ON COLUMN "public"."job_runtime_state"."last_started_at" IS '上次开始时间';
COMMENT ON COLUMN "public"."job_runtime_state"."last_finished_at" IS '上次结束时间';
COMMENT ON COLUMN "public"."job_runtime_state"."last_status" IS '上次运行状态（SUCCESS/FAILED/RUNNING）';
COMMENT ON COLUMN "public"."job_runtime_state"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."job_runtime_state" IS '任务运行时状态（水位线断点等）';

-- ----------------------------
-- Table structure for job_schedule
-- ----------------------------
DROP TABLE IF EXISTS "public"."job_schedule";
CREATE TABLE "public"."job_schedule" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "cron_expr" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "enabled" bool NOT NULL DEFAULT true,
  "max_concurrency" int4 NOT NULL DEFAULT 10,
  "batch_size" int4 NOT NULL DEFAULT 1000,
  "http_timeout_sec" int4 NOT NULL DEFAULT 20,
  "params" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "sync_mode" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'FULL'::character varying,
  "sync_limit" int8 NOT NULL DEFAULT 0,
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."job_schedule" OWNER TO "postgres";
COMMENT ON COLUMN "public"."job_schedule"."id" IS '自增主键';
COMMENT ON COLUMN "public"."job_schedule"."job_code" IS '任务编码（唯一）';
COMMENT ON COLUMN "public"."job_schedule"."cron_expr" IS 'Cron 表达式';
COMMENT ON COLUMN "public"."job_schedule"."enabled" IS '任务开关';
COMMENT ON COLUMN "public"."job_schedule"."max_concurrency" IS '并发上限';
COMMENT ON COLUMN "public"."job_schedule"."batch_size" IS '批量提交大小';
COMMENT ON COLUMN "public"."job_schedule"."http_timeout_sec" IS 'HTTP 超时（秒）';
COMMENT ON COLUMN "public"."job_schedule"."params" IS '自定义业务参数（JSON），如：{"syncHotelDetail":true,"syncHotelName":true}';
COMMENT ON COLUMN "public"."job_schedule"."sync_mode" IS '同步范围：FULL=全量；LIMIT=仅同步指定条数';
COMMENT ON COLUMN "public"."job_schedule"."sync_limit" IS '当 sync_mode=LIMIT 时的最大同步条数（0表示不限制）';
COMMENT ON COLUMN "public"."job_schedule"."remark" IS '备注';
COMMENT ON COLUMN "public"."job_schedule"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."job_schedule" IS '任务调度配置（DB驱动Cron），含业务参数与同步范围';

-- ----------------------------
-- Table structure for sync_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."sync_log";
CREATE TABLE "public"."sync_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "trace_id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "started_at" timestamptz(6) NOT NULL,
  "finished_at" timestamptz(6),
  "cost_seconds" int4,
  "total_ids" int8 DEFAULT 0,
  "total_details" int8 DEFAULT 0,
  "success_count" int8 DEFAULT 0,
  "fail_count" int8 DEFAULT 0,
  "status" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'RUNNING'::character varying,
  "message" text COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."sync_log" OWNER TO "postgres";
COMMENT ON COLUMN "public"."sync_log"."id" IS '自增主键';
COMMENT ON COLUMN "public"."sync_log"."job_code" IS '任务编码';
COMMENT ON COLUMN "public"."sync_log"."trace_id" IS '运行追踪ID（与 api_request_log 关联）';
COMMENT ON COLUMN "public"."sync_log"."started_at" IS '开始时间';
COMMENT ON COLUMN "public"."sync_log"."finished_at" IS '结束时间';
COMMENT ON COLUMN "public"."sync_log"."cost_seconds" IS '总耗时（秒）';
COMMENT ON COLUMN "public"."sync_log"."total_ids" IS '本次运行期间拉取到的酒店ID数量';
COMMENT ON COLUMN "public"."sync_log"."total_details" IS '成功解析并落地的酒店详情记录数';
COMMENT ON COLUMN "public"."sync_log"."success_count" IS '成功计数';
COMMENT ON COLUMN "public"."sync_log"."fail_count" IS '失败计数';
COMMENT ON COLUMN "public"."sync_log"."status" IS '运行状态（RUNNING/SUCCESS/FAILED/PARTIAL）';
COMMENT ON COLUMN "public"."sync_log"."message" IS '附加信息/备注';
COMMENT ON TABLE "public"."sync_log" IS '同步日志汇总（全局计数器）';

-- ----------------------------
-- Table structure for sync_log_detail
-- ----------------------------
DROP TABLE IF EXISTS "public"."sync_log_detail";
CREATE TABLE "public"."sync_log_detail" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "sync_log_id" int8 NOT NULL,
  "hotel_id" int8,
  "stage" varchar(32) COLLATE "pg_catalog"."default",
  "error_code" varchar(64) COLLATE "pg_catalog"."default",
  "error_message" text COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."sync_log_detail" OWNER TO "postgres";
COMMENT ON COLUMN "public"."sync_log_detail"."id" IS '自增主键';
COMMENT ON COLUMN "public"."sync_log_detail"."sync_log_id" IS '关联的同步日志ID';
COMMENT ON COLUMN "public"."sync_log_detail"."hotel_id" IS '酒店ID（可为空）';
COMMENT ON COLUMN "public"."sync_log_detail"."stage" IS '阶段（IDS_FETCH/DETAIL_FETCH/TRANSFORM/SINK/INDEX_*）';
COMMENT ON COLUMN "public"."sync_log_detail"."error_code" IS '错误码';
COMMENT ON COLUMN "public"."sync_log_detail"."error_message" IS '错误信息';
COMMENT ON COLUMN "public"."sync_log_detail"."created_at" IS '记录时间';
COMMENT ON TABLE "public"."sync_log_detail" IS '同步失败明细（支持按 sync_log_id 重跑补偿）';

-- ----------------------------
-- Indexes structure for table api_request_log
-- ----------------------------
CREATE INDEX "idx_api_log_job" ON "public"."api_request_log" USING btree (
  "job_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_status" ON "public"."api_request_log" USING btree (
  "response_status" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_time" ON "public"."api_request_log" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_trace" ON "public"."api_request_log" USING btree (
  "trace_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table api_request_log
-- ----------------------------
ALTER TABLE "public"."api_request_log" ADD CONSTRAINT "api_request_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table hotels
-- ----------------------------
CREATE INDEX "idx_hotels_brand" ON "public"."hotels" USING btree (
  "hotel_brand_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "hotel_brand_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_city" ON "public"."hotels" USING btree (
  "city_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "city_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_continent" ON "public"."hotels" USING btree (
  "continent_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "continent_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_country" ON "public"."hotels" USING btree (
  "country_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "country_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "country_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_hotel_group" ON "public"."hotels" USING btree (
  "hotel_group_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "hotel_group_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_hotel_id" ON "public"."hotels" USING btree (
  "hotel_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_region" ON "public"."hotels" USING btree (
  "region_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "region_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_tag_source" ON "public"."hotels" USING btree (
  "tag_source" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table hotels
-- ----------------------------
ALTER TABLE "public"."hotels" ADD CONSTRAINT "uk_hotels_source_hotel" UNIQUE ("source", "hotel_id");

-- ----------------------------
-- Primary Key structure for table hotels
-- ----------------------------
ALTER TABLE "public"."hotels" ADD CONSTRAINT "hotels_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Uniques structure for table job_runtime_state
-- ----------------------------
ALTER TABLE "public"."job_runtime_state" ADD CONSTRAINT "job_runtime_state_job_code_key" UNIQUE ("job_code");

-- ----------------------------
-- Primary Key structure for table job_runtime_state
-- ----------------------------
ALTER TABLE "public"."job_runtime_state" ADD CONSTRAINT "job_runtime_state_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table job_schedule
-- ----------------------------
CREATE INDEX "idx_job_schedule_enabled" ON "public"."job_schedule" USING btree (
  "enabled" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table job_schedule
-- ----------------------------
ALTER TABLE "public"."job_schedule" ADD CONSTRAINT "job_schedule_job_code_key" UNIQUE ("job_code");

-- ----------------------------
-- Primary Key structure for table job_schedule
-- ----------------------------
ALTER TABLE "public"."job_schedule" ADD CONSTRAINT "job_schedule_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table sync_log
-- ----------------------------
CREATE INDEX "idx_sync_log_job_code" ON "public"."sync_log" USING btree (
  "job_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_started_at" ON "public"."sync_log" USING btree (
  "started_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_status" ON "public"."sync_log" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table sync_log
-- ----------------------------
ALTER TABLE "public"."sync_log" ADD CONSTRAINT "sync_log_job_code_trace_id_key" UNIQUE ("job_code", "trace_id");

-- ----------------------------
-- Primary Key structure for table sync_log
-- ----------------------------
ALTER TABLE "public"."sync_log" ADD CONSTRAINT "sync_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table sync_log_detail
-- ----------------------------
CREATE INDEX "idx_sync_log_detail_hotel_id" ON "public"."sync_log_detail" USING btree (
  "hotel_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_detail_log_id" ON "public"."sync_log_detail" USING btree (
  "sync_log_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_detail_stage" ON "public"."sync_log_detail" USING btree (
  "stage" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table sync_log_detail
-- ----------------------------
ALTER TABLE "public"."sync_log_detail" ADD CONSTRAINT "sync_log_detail_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table sync_log_detail
-- ----------------------------
ALTER TABLE "public"."sync_log_detail" ADD CONSTRAINT "sync_log_detail_sync_log_id_fkey" FOREIGN KEY ("sync_log_id") REFERENCES "public"."sync_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;



-- 结束
