-- ===========================
-- 搜索日志表
-- 用途：记录用户搜索行为，用于搜索质量分析和优化
-- ===========================

-- ----------------------------
-- Table structure for search_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."search_logs";
CREATE TABLE "public"."search_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "query" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "tag_source" varchar(32) COLLATE "pg_catalog"."default",
  "result_count" int4,
  "clicked_hotel_id" int8,
  "click_position" int4,
  "duration_ms" int8,
  "user_id" int8,
  "user_ip" varchar(64) COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

ALTER TABLE "public"."search_logs" OWNER TO "postgres";

-- ----------------------------
-- 表注释
-- ----------------------------
COMMENT ON TABLE "public"."search_logs" IS '搜索日志（用于搜索质量分析）';

-- ----------------------------
-- 字段注释
-- ----------------------------
COMMENT ON COLUMN "public"."search_logs"."id" IS '自增主键';
COMMENT ON COLUMN "public"."search_logs"."query" IS '用户查询词';
COMMENT ON COLUMN "public"."search_logs"."tag_source" IS '业务域（CN/INTL/HMT）';
COMMENT ON COLUMN "public"."search_logs"."result_count" IS '搜索结果数量';
COMMENT ON COLUMN "public"."search_logs"."clicked_hotel_id" IS '点击的酒店ID';
COMMENT ON COLUMN "public"."search_logs"."click_position" IS '点击位置（排名）';
COMMENT ON COLUMN "public"."search_logs"."duration_ms" IS '查询耗时（毫秒）';
COMMENT ON COLUMN "public"."search_logs"."user_id" IS '用户ID（可选）';
COMMENT ON COLUMN "public"."search_logs"."user_ip" IS '用户IP地址';
COMMENT ON COLUMN "public"."search_logs"."created_at" IS '创建时间';

-- ----------------------------
-- Indexes structure for table search_logs
-- ----------------------------
CREATE INDEX "idx_search_logs_query" ON "public"."search_logs" USING btree (
  "query" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "idx_search_logs_created_at" ON "public"."search_logs" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);

CREATE INDEX "idx_search_logs_result_count" ON "public"."search_logs" USING btree (
  "result_count" "pg_catalog"."int4_ops" ASC NULLS LAST
);

CREATE INDEX "idx_search_logs_tag_source" ON "public"."search_logs" USING btree (
  "tag_source" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table search_logs
-- ----------------------------
ALTER TABLE "public"."search_logs" ADD CONSTRAINT "search_logs_pkey" PRIMARY KEY ("id");
