/*
 Navicat Premium Dump SQL

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 120022 (120022)
 Source Host           : localhost:5432
 Source Catalog        : hotel-search
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120022 (120022)
 File Encoding         : 65001

 Date: 04/12/2025 18:19:15
*/


-- ----------------------------
-- Table structure for api_request_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."api_request_log";
CREATE TABLE "public"."api_request_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "trace_id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "http_method" varchar(8) COLLATE "pg_catalog"."default" NOT NULL,
  "url" text COLLATE "pg_catalog"."default" NOT NULL,
  "request_headers" jsonb NOT NULL,
  "response_status" int4,
  "duration_ms" int4,
  "request_body_compressed" bytea,
  "response_body_compressed" bytea,
  "request_size_bytes" int4,
  "response_size_bytes" int4,
  "compression" "public"."compression_codec" NOT NULL DEFAULT 'gzip'::compression_codec,
  "app" varchar(64) COLLATE "pg_catalog"."default",
  "timestamp_utc" timestamptz(6) NOT NULL DEFAULT now(),
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
)
;
ALTER TABLE "public"."api_request_log" OWNER TO "postgres";
COMMENT ON COLUMN "public"."api_request_log"."id" IS '自增主键';
COMMENT ON COLUMN "public"."api_request_log"."trace_id" IS '与同步日志相关联的追踪ID';
COMMENT ON COLUMN "public"."api_request_log"."job_code" IS '任务编码（对应 job_schedule.job_code）';
COMMENT ON COLUMN "public"."api_request_log"."source" IS '来源标识（CN/INTL 等）';
COMMENT ON COLUMN "public"."api_request_log"."http_method" IS 'HTTP 方法（GET/POST 等）';
COMMENT ON COLUMN "public"."api_request_log"."url" IS '请求URL';
COMMENT ON COLUMN "public"."api_request_log"."request_headers" IS '请求头（JSON）';
COMMENT ON COLUMN "public"."api_request_log"."response_status" IS '响应状态码';
COMMENT ON COLUMN "public"."api_request_log"."duration_ms" IS '请求耗时（毫秒）';
COMMENT ON COLUMN "public"."api_request_log"."request_body_compressed" IS '压缩后的请求体字节';
COMMENT ON COLUMN "public"."api_request_log"."response_body_compressed" IS '压缩后的响应体字节';
COMMENT ON COLUMN "public"."api_request_log"."request_size_bytes" IS '请求体大小（字节）';
COMMENT ON COLUMN "public"."api_request_log"."response_size_bytes" IS '响应体大小（字节）';
COMMENT ON COLUMN "public"."api_request_log"."compression" IS '压缩算法：none/gzip/zstd/lz4，由应用层负责压缩与解压';
COMMENT ON COLUMN "public"."api_request_log"."app" IS '供应商应用标识';
COMMENT ON COLUMN "public"."api_request_log"."timestamp_utc" IS '请求发生时间（UTC）';
COMMENT ON COLUMN "public"."api_request_log"."created_at" IS '记录创建时间';
COMMENT ON TABLE "public"."api_request_log" IS '外部API请求日志（请求/响应原文采用压缩字节存储）';

-- ----------------------------
-- Records of api_request_log
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for hotel_poi
-- ----------------------------
DROP TABLE IF EXISTS "public"."hotel_poi";
CREATE TABLE "public"."hotel_poi" (
  "id" text COLLATE "pg_catalog"."default" NOT NULL,
  "name" text COLLATE "pg_catalog"."default",
  "type" text COLLATE "pg_catalog"."default",
  "typeCode" text COLLATE "pg_catalog"."default",
  "address" text COLLATE "pg_catalog"."default",
  "location" text COLLATE "pg_catalog"."default",
  "tel" text COLLATE "pg_catalog"."default",
  "pcode" text COLLATE "pg_catalog"."default",
  "pname" text COLLATE "pg_catalog"."default",
  "cityname" text COLLATE "pg_catalog"."default",
  "adname" text COLLATE "pg_catalog"."default",
  "adcode" text COLLATE "pg_catalog"."default",
  "citycode" text COLLATE "pg_catalog"."default",
  "parent" text COLLATE "pg_catalog"."default",
  "distance" text COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."hotel_poi" OWNER TO "postgres";

-- ----------------------------
-- Records of hotel_poi
-- ----------------------------
BEGIN;
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG72JYC', '五方天雅汽车服务园', '汽车服务;汽车配件销售;汽车配件销售', '010800', 'S50东五环g1号', '116.541865,39.864056', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000AA160J', '永同昌·西国贸汽服基地', '汽车服务;汽车配件销售;汽车配件销售', '010800', '丰益桥西南三环', '116.313559,39.855339', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A8UC7W', '城环城国际汽配城', '汽车服务;汽车配件销售;汽车配件销售|公司企业;公司;公司|汽车服务;汽车养护/装饰;汽车养护', '010800|170200|010400', '南四环东路69号', '116.455386,39.835595', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A9KHDR', '北京市旧机动车交易市场', '汽车服务;二手车交易;二手车交易', '011000', '南四环西路123号', '116.309142,39.833125', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7HUJP', '回龙观北郊汽配城现代起亚', '汽车服务;汽车配件销售;汽车配件销售', '010800', '回龙观北郊汽配城配件厅二厅A14', '116.306719,40.080575', '', '110000', '北京市', '北京市', '昌平区', '110114', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFI93IIL', '大南郊汽配城', '汽车服务;汽车配件销售;汽车配件销售', '010800', 'S317(京周路)', '116.106554,39.723979', '', '110000', '北京市', '北京市', '房山区', '110111', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG7VTTM', '北京排山汽车城', '公司企业;公司;公司|汽车服务;洗车场;洗车场|汽车销售;汽车销售;汽车销售', '170200|010500|020000', '十里堡镇101国道61公里+700米处路北', '116.794475,40.356157', '', '110000', '北京市', '北京市', '密云区', '110118', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7QZ5C', '北辰亚运村二手车交易市场', '汽车服务;二手车交易;二手车交易', '011000', '天通苑东三旗村', '116.414629,40.095739', '', '110000', '北京市', '北京市', '昌平区', '110114', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0KADHRLI4', '酷车小镇(停车场店)', '汽车服务;汽车服务相关;汽车服务相关', '010000', '金蝉西路甲1号院酷车小镇D3区9号', '116.504051,39.871249', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFJV9QR6', '北京市顺义区南法信众合汽配城', '汽车服务;汽车服务相关;汽车服务相关', '010000', '顺平路南法信段10号', '116.613925,40.115669', '', '110000', '北京市', '北京市', '顺义区', '110113', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0J0A18O56', '花乡二手车自营展厅', '汽车服务;二手车交易;二手车交易', '011000', '南四环西路123号', '116.309161,39.833369', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFGHT87W', '丰益桥西国贸汽车配件城', '汽车服务;汽车配件销售;汽车配件销售', '010800', '丰益桥西国贸汽配基地', '116.315409,39.856201', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFGAQQ2Q', '中国石化土沟西加油站', '汽车服务;加油站;中国石化', '010101', '京承高速进京方向,土沟服务区内(六环至五环之间)', '116.482401,40.127894', '', '110000', '北京市', '北京市', '昌平区', '110114', '010', 'B000A7ZXKU', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFMGLJ2M', '天盛加油站', '汽车服务;加油站;加油站', '010100', '中关村科技园区通州园光机电一体化产业基地兴光六街1号', '116.569027,39.809798', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0J2KU8E9F', '北京城区草桥汽配城', '汽车服务;汽车配件销售;汽车配件销售', '010800', '草桥东路与赵村店路交叉口南100米', '116.358831,39.839112', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG6CWHP', '中国石化观音堂西加油站', '汽车服务;加油站;中国石化', '010101', '王四营乡南花园村五环路观音堂段西侧', '116.547625,39.887474', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', 'B000A83D5A', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A8VRBX', '中国石化柳村南加油站', '汽车服务;加油站;中国石化', '010101', '南四环西路64号', '116.328054,39.830378', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', 'B000A81HA2', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFLNFO24', '中国石化礼贤南加油站', '汽车服务;加油站;中国石化', '010101', '新机场高速公路', '116.409331,39.542083', '', '110000', '北京市', '北京市', '大兴区', '110115', '010', 'BZD7PW009S', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A83MIQ', '中国石油京胜望京南加油站', '汽车服务;加油站;中国石油', '010102', '来广营乡(广泽桥东200米)', '116.482329,40.013817', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', 'B000A83FX6', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0IDBRM0EF', '老包修车(阜石路店)奔驰宝马奥迪维修', '汽车服务;汽车救援;汽车救援|汽车服务;汽车养护/装饰;汽车养护|汽车维修;汽车维修;汽车维修', '010700|010400|030000', '阜石路甲19号', '116.259733,39.926195', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG8PSP4', '马驹桥汽车服务中心(宏仁家园西北)', '汽车服务;汽车配件销售;汽车配件销售', '010800', '西周路马驹桥汽配城', '116.558145,39.750713', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0I1X5QGXC', '北京盛鑫旧机动车交易市场', '汽车服务;二手车交易;二手车交易|汽车销售;汽车销售;汽车销售', '011000|020000', '王四营乡五方天雅汽配城东门A8区82-126号', '116.546837,39.863009', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0KKBUIOIV', '北京市通州区汽配城', '汽车服务;汽车配件销售;汽车配件销售', '010800', '马驹桥西店村', '116.558149,39.750708', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A83K20', '中国石油京胜望京北加油站', '汽车服务;加油站;中国石油', '010102', '来广营(广泽桥东200米)', '116.485318,40.013929', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', 'B000A83FX5', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0KUFM5161', '小米汽车交付中心(北京小米未来产业园店)', '汽车服务;汽车服务相关;汽车服务相关', '010000', '七辛北街与朱辛庄中路交叉口小米智能工厂二期K栋', '116.305060,40.107023', '', '110000', '北京市', '北京市', '昌平区', '110114', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG0ZUFL', '中国石化天通苑加油站', '汽车服务;加油站;中国石化', '010101', '立汤路太平庄中街京妮儿童汇旁', '116.413943,40.068449', '', '110000', '北京市', '北京市', '昌平区', '110114', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7742C', '小海豚加油站(小红门站)', '汽车服务;加油站;加油站', '010100', '南四环东路53号', '116.461453,39.834182', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0H26MZHET', '小海豚加油站', '汽车服务;加油站;加油站', '010100', '永顺地区北马庄村(通顺路路东翠福园小区向)', '116.657130,39.949608', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0LGBK0V0E', '京东养车(维修改装中心•超级贴膜工厂)', '汽车服务;汽车养护/装饰;汽车养护', '010400', '科创二街6号', '116.533637,39.816635', '', '110000', '北京市', '北京市', '大兴区', '110115', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0JGNMTXXG', '京东养车(北京西站店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '莲花池东路53号(北京西站地铁站北出口步行440米)', '116.320012,39.898064', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0JG7ZSTRS', '京东养车(万丰路店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '卢沟桥七里庄578号(七里庄地铁站B东北口步行280米)', '116.295313,39.870005', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140U2Z6', '海逸购物广场', '购物服务;商场;普通商场|购物服务;商场;购物中心', '060102|060101', '江南大道中110号(市二宫地铁站E口步行370米)', '113.271126,23.101901', '', '440000', '广东省', '广州市', '海珠区', '440105', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0IKTRO2Y2', '京东养车(德胜门店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '德胜门西大街与桦皮厂胡同交叉口西南60米', '116.358318,39.944029', '', '110000', '北京市', '北京市', '西城区', '110102', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0IKGU86UQ', '京东养车(时代财富店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '航丰路1号', '116.286229,39.830694', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0H32Z5E4C', '京东养车(阜成路店)', '汽车服务;汽车养护/装饰;汽车养护|汽车维修;汽车维修;汽车维修', '010400|030000', '阜成路111号', '116.281724,39.924635', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0H0A7UQCJ', '京东养车(小屯路店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '小屯路19号', '116.253512,39.880022', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000AA9I3O', '月福汽车装饰(燕莎店)', '汽车服务;汽车养护/装饰;汽车养护', '010400', '将台乡亮马桥路5号', '116.481809,39.960519', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFG7476T', '马驹桥石化加油站', '汽车服务;加油站;加油站', '010100', '景盛北三街与马朱路交叉口', '116.567811,39.745779', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFGYRY0C', '中国石油首汽2号加油站', '汽车服务;加油站;中国石油|公司企业;公司;公司', '010102|170200', '紫竹院南路甲3号', '116.319507,39.938515', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0ID5SL40X', '京东养车(次渠北里店)', '汽车服务;汽车养护/装饰;汽车养护|汽车服务;洗车场;洗车场|汽车维修;汽车维修;汽车维修', '010400|010500|030000', '次渠北里三区138号楼一层101', '116.574563,39.806172', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7GSK9', '中国石化西黄庄加油站', '汽车服务;加油站;中国石化', '010101', '昆明湖南路37号', '116.276872,39.953217', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0I39S1NT5', '城南加油站', '汽车服务;加油站;加油站', '010100', '九棵树西路108号', '116.647528,39.880048', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A8UT7R', '中国石化裕翠加油站', '汽车服务;加油站;中国石化', '010101', '西翠路15号', '116.282867,39.917996', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A01DA4', '中国石化安宁庄加油站', '汽车服务;加油站;中国石化', '010101', '东北旺乡安宁庄村西侧', '116.320494,40.049008', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFIB5PGE', '北京丰台区草桥汽配城机油三滤防冻液', '汽车服务;汽车配件销售;汽车配件销售', '010800', '草桥东路汇丰汽配城5厅17号', '116.357384,39.837854', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A95CH4', '中国石油首汽6号加油站', '汽车服务;加油站;中国石油', '010102', '新源南路甲7号', '116.453947,39.948898', '', '110000', '北京市', '北京市', '朝阳区', '110105', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7YW1O', '中国石化海淀实华加油站', '汽车服务;加油站;中国石化', '010101', '文慧园北路10号', '116.361793,39.956103', '', '110000', '北京市', '北京市', '海淀区', '110108', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFKXRM6U', '中国石化科创街加油站', '汽车服务;加油站;中国石化', '010101', '中关村科技园区通州园光机电一体化产业基地经海六路16号', '116.559524,39.800812', '', '110000', '北京市', '北京市', '通州区', '110112', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A7W3AH', '中国石油特许加盟石京源加油站', '汽车服务;加油站;中国石油', '010102', '莲石西路', '116.200882,39.889595', '', '110000', '北京市', '北京市', '石景山区', '110107', '010', 'BZDBPU00Y5', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000AA0MKC', '靛厂路加油站', '汽车服务;加油站;加油站', '010100', '靛厂路46号附近', '116.280501,39.890039', '', '110000', '北京市', '北京市', '丰台区', '110106', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B000A8ZOA9', '顺潮东汽车交易市场', '汽车服务;二手车交易;二手车交易', '011000', '潮白河永久桥左堤路1号', '116.682077,40.138256', '', '110000', '北京市', '北京市', '顺义区', '110113', '010', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFJ9SWQX', '天环Parc Central西塔', '购物服务;商场;购物中心', '060101', '天河路218号(天河南地铁站A口步行130米)', '113.324299,23.132373', '', '440000', '广东省', '广州市', '天河区', '440106', '020', 'B0FFG1OCOA', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141KN1L', '麒麟广场', '购物服务;商场;购物中心', '060101', '黄梅路与康政街交叉口东80米', '113.507234,22.819696', '', '440000', '广东省', '广州市', '南沙区', '440115', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFILWI5N', '亚运城广场', '购物服务;商场;购物中心', '060101', '亚运城康体路43号', '113.476557,22.941816', '', '440000', '广东省', '广州市', '番禺区', '440113', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFFS9X3R', '天河汇商业广场', '购物服务;商场;购物中心', '060101', '天河直街160号', '113.317291,23.139306', '', '440000', '广东省', '广州市', '天河区', '440106', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFFGUP31', '海印又一城', '购物服务;商场;购物中心', '060101', '番禺大道北383号', '113.349172,22.998902', '', '440000', '广东省', '广州市', '番禺区', '440113', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFFX8OUU', '动漫星城', '购物服务;商场;购物中心', '060101', '吉祥路1号(公园前地铁站F口步行60米)', '113.264941,23.125780', '', '440000', '广东省', '广州市', '越秀区', '440104', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFI64D9F', '莱茵汇大广场', '购物服务;商场;购物中心', '060101', '江埔街道从城大道2号', '113.601881,23.526520', '', '440000', '广东省', '广州市', '从化区', '440117', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141IFCP', '广州白云万达广场', '购物服务;商场;购物中心', '060101', '云城东路501号', '113.266727,23.172397', '', '440000', '广东省', '广州市', '白云区', '440111', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141IEY6', '广州大学商业中心', '购物服务;商场;购物中心', '060101', '大学城中环西路230号', '113.372703,23.041679', '', '440000', '广东省', '广州市', '番禺区', '440113', '020', 'B00140AM0Y', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140WEVB', '雄洲城', '购物服务;商场;购物中心', '060101', '同和街道石桥头社区广州大道北2091号', '113.325061,23.198055', '', '440000', '广东省', '广州市', '白云区', '440111', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140WADY', '都得利广场', '购物服务;商场;购物中心|购物服务;商场;普通商场', '060101|060102', '河沙桥中北路2-4号(河沙地铁站B口步行240米)', '113.219820,23.134672', '', '440000', '广东省', '广州市', '荔湾区', '440103', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFHWIDJ0', '花地商业中心西区', '购物服务;商场;购物中心', '060101', '百花路8-10号', '113.229039,23.095161', '', '440000', '广东省', '广州市', '荔湾区', '440103', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140V6AN', '金佳活力城', '购物服务;商场;购物中心', '060101', '市桥大北路延长段东涌路92-94号', '113.367437,22.935279', '', '440000', '广东省', '广州市', '番禺区', '440113', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140WBA9', '东汇城2期', '购物服务;商场;购物中心', '060101', '荔城街观翠路10号106房', '113.819518,23.285226', '', '440000', '广东省', '广州市', '增城区', '440118', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140A53D', '百盛', '购物服务;商场;购物中心|购物服务;服装鞋帽皮具店;服装鞋帽皮具店', '060101|061100', '新中路52号', '113.207254,23.376968', '', '440000', '广东省', '广州市', '花都区', '440114', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFHTJ9X6', '馨润·港荟', '购物服务;商场;购物中心', '060101', '东晓南路盈丰路馨润尚寓二期首2层', '113.297348,23.068590', '', '440000', '广东省', '广州市', '海珠区', '440105', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFI5H7IB', '花都区联合广场', '购物服务;商场;购物中心', '060101', '狮岭镇宝峰南路6-11号', '113.174565,23.463471', '', '440000', '广东省', '广州市', '花都区', '440114', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B0FFHISC5I', '天成购物广场', '购物服务;商场;购物中心', '060101', '均禾街长红村双和庄东路8号', '113.308770,23.264643', '', '440000', '广东省', '广州市', '白云区', '440111', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141R8NA', '乐峰广场', '购物服务;商场;购物中心', '060101', '工业大道北107号', '113.259082,23.088633', '', '440000', '广东省', '广州市', '海珠区', '440105', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141IH9C', '龙洞购物中心', '购物服务;商场;购物中心', '060101', '龙洞迎龙路6号(植物园地铁站D口步行210米)', '113.366744,23.193524', '', '440000', '广东省', '广州市', '天河区', '440106', '020', 'B0FFHEZ8S7', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141I9WG', '万国奥特莱斯', '购物服务;商场;购物中心', '060101', '江湾路285号', '113.273145,23.101781', '', '440000', '广东省', '广州市', '海珠区', '440105', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141SB8A', '骏唐购物广场', '购物服务;商场;购物中心', '060101', '中山大道西777号棠下丰乐路123号', '113.383507,23.126043', '', '440000', '广东省', '广州市', '天河区', '440106', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00141KZPA', '聚味珠江道美食广场(猎德大道辅路店)', '购物服务;商场;购物中心|购物服务;商场;普通商场|餐饮服务;餐饮相关场所;餐饮相关', '060101|060102|050000', '猎德大道20号(猎德地铁站C口步行410米)', '113.334379,23.119879', '', '440000', '广东省', '广州市', '天河区', '440106', '020', '', '');
INSERT INTO "public"."hotel_poi" ("id", "name", "type", "typeCode", "address", "location", "tel", "pcode", "pname", "cityname", "adname", "adcode", "citycode", "parent", "distance") VALUES ('B00140V427', '万民广场(花都店)', '购物服务;商场;购物中心', '060101', '建设北路72号', '113.204634,23.386293', '', '440000', '广东省', '广州市', '花都区', '440114', '020', '', '');
COMMIT;

-- ----------------------------
-- Table structure for hotels
-- ----------------------------
DROP TABLE IF EXISTS "public"."hotels";
CREATE TABLE "public"."hotels" (
  "id" int8 NOT NULL DEFAULT nextval('hotels_staging_id_seq'::regclass),
  "source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "tag_source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "hotel_id" int8 NOT NULL,
  "hotel_name_cn" text COLLATE "pg_catalog"."default",
  "hotel_name_en" text COLLATE "pg_catalog"."default",
  "new_hotel_name_cn" text COLLATE "pg_catalog"."default",
  "new_hotel_name_en" text COLLATE "pg_catalog"."default",
  "country_cn" varchar(100) COLLATE "pg_catalog"."default",
  "country_en" varchar(100) COLLATE "pg_catalog"."default",
  "country_code" varchar(10) COLLATE "pg_catalog"."default",
  "city_cn" varchar(100) COLLATE "pg_catalog"."default",
  "city_en" varchar(100) COLLATE "pg_catalog"."default",
  "region_cn" varchar(100) COLLATE "pg_catalog"."default",
  "region_en" varchar(100) COLLATE "pg_catalog"."default",
  "continent_cn" varchar(50) COLLATE "pg_catalog"."default",
  "continent_en" varchar(50) COLLATE "pg_catalog"."default",
  "address_cn" text COLLATE "pg_catalog"."default",
  "address_en" text COLLATE "pg_catalog"."default",
  "longitude" numeric(10,7),
  "latitude" numeric(10,7),
  "hotel_group_cn" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_group_en" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_brand_cn" varchar(200) COLLATE "pg_catalog"."default",
  "hotel_brand_en" varchar(200) COLLATE "pg_catalog"."default",
  "fetched_at" timestamptz(6) DEFAULT CURRENT_TIMESTAMP,
  "description_cn" text COLLATE "pg_catalog"."default",
  "description_en" text COLLATE "pg_catalog"."default",
  "raw_compressed" text COLLATE "pg_catalog"."default" DEFAULT ''::text,
  "updated_at" timestamptz(6) DEFAULT CURRENT_TIMESTAMP
)
;
ALTER TABLE "public"."hotels" OWNER TO "postgres";
COMMENT ON COLUMN "public"."hotels"."id" IS '主键ID（自增）';
COMMENT ON COLUMN "public"."hotels"."source" IS '数据源：Elong=艺龙；Agoda=安可达';
COMMENT ON COLUMN "public"."hotels"."tag_source" IS '标签源：CN=国内；INTL=国际；GAT=港澳台';
COMMENT ON COLUMN "public"."hotels"."hotel_id" IS '酒店ID（供应商体系内的酒店标识）';
COMMENT ON COLUMN "public"."hotels"."hotel_name_cn" IS '酒店中文名（从原文解析或翻译得到）';
COMMENT ON COLUMN "public"."hotels"."hotel_name_en" IS '酒店英文名（从原文解析）';
COMMENT ON COLUMN "public"."hotels"."new_hotel_name_cn" IS '新中文名（数据源返回的标准化名称或内部清洗后的结果）';
COMMENT ON COLUMN "public"."hotels"."new_hotel_name_en" IS '新英文名（数据源返回的标准化名称或内部清洗后的结果）';
COMMENT ON COLUMN "public"."hotels"."country_cn" IS '国家中文名';
COMMENT ON COLUMN "public"."hotels"."country_en" IS '国家英文名';
COMMENT ON COLUMN "public"."hotels"."country_code" IS '国家代码（ISO 3166-1 alpha-2，如 CN/HK/MO/TW/US 等）';
COMMENT ON COLUMN "public"."hotels"."city_cn" IS '城市中文名';
COMMENT ON COLUMN "public"."hotels"."city_en" IS '城市英文名';
COMMENT ON COLUMN "public"."hotels"."region_cn" IS '区域/区县中文名';
COMMENT ON COLUMN "public"."hotels"."region_en" IS '区域/区县英文名';
COMMENT ON COLUMN "public"."hotels"."continent_cn" IS '洲中文名（如：亚洲、欧洲、北美洲等）';
COMMENT ON COLUMN "public"."hotels"."continent_en" IS '洲英文名（如：Asia、Europe、North America 等）';
COMMENT ON COLUMN "public"."hotels"."address_cn" IS '酒店地址中文原文';
COMMENT ON COLUMN "public"."hotels"."address_en" IS '酒店地址英文原文';
COMMENT ON COLUMN "public"."hotels"."longitude" IS '经度（-180 ~ 180）';
COMMENT ON COLUMN "public"."hotels"."latitude" IS '纬度（-90 ~ 90）';
COMMENT ON COLUMN "public"."hotels"."hotel_group_cn" IS '酒店集团中文名（如：万豪、希尔顿等）';
COMMENT ON COLUMN "public"."hotels"."hotel_group_en" IS '酒店集团英文名（如：Marriott、Hilton 等）';
COMMENT ON COLUMN "public"."hotels"."hotel_brand_cn" IS '酒店品牌中文名（如：JW万豪、康莱德等）';
COMMENT ON COLUMN "public"."hotels"."hotel_brand_en" IS '酒店品牌英文名（如：JW Marriott、Conrad 等）';
COMMENT ON COLUMN "public"."hotels"."fetched_at" IS '数据抓取时间（入库时间戳）';
COMMENT ON COLUMN "public"."hotels"."description_cn" IS '酒店描述（中文）';
COMMENT ON COLUMN "public"."hotels"."description_en" IS '酒店描述（英文）';
COMMENT ON COLUMN "public"."hotels"."raw_compressed" IS '酒店原文（GIZP 压缩）';
COMMENT ON COLUMN "public"."hotels"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."hotels" IS '酒店详情 Staging 表：存放采集到的酒店原文与基础解析字段';

-- ----------------------------
-- Records of hotels
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for job_runtime_state
-- ----------------------------
DROP TABLE IF EXISTS "public"."job_runtime_state";
CREATE TABLE "public"."job_runtime_state" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "watermark_max_hotel_id" int8 NOT NULL DEFAULT 0,
  "last_started_at" timestamptz(6),
  "last_finished_at" timestamptz(6),
  "last_status" varchar(20) COLLATE "pg_catalog"."default",
  "updated_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."job_runtime_state" OWNER TO "postgres";
COMMENT ON COLUMN "public"."job_runtime_state"."id" IS '自增主键';
COMMENT ON COLUMN "public"."job_runtime_state"."job_code" IS '任务编码';
COMMENT ON COLUMN "public"."job_runtime_state"."watermark_max_hotel_id" IS '基于供应商API的 maxHotelId 断点续跑水位';
COMMENT ON COLUMN "public"."job_runtime_state"."last_started_at" IS '上次开始时间';
COMMENT ON COLUMN "public"."job_runtime_state"."last_finished_at" IS '上次结束时间';
COMMENT ON COLUMN "public"."job_runtime_state"."last_status" IS '上次运行状态（SUCCESS/FAILED/RUNNING）';
COMMENT ON COLUMN "public"."job_runtime_state"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."job_runtime_state" IS '任务运行时状态（水位线断点等）';

-- ----------------------------
-- Records of job_runtime_state
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for job_schedule
-- ----------------------------
DROP TABLE IF EXISTS "public"."job_schedule";
CREATE TABLE "public"."job_schedule" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "cron_expr" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "enabled" bool NOT NULL DEFAULT true,
  "max_concurrency" int4 NOT NULL DEFAULT 10,
  "batch_size" int4 NOT NULL DEFAULT 1000,
  "http_timeout_sec" int4 NOT NULL DEFAULT 20,
  "params" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "sync_mode" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'FULL'::character varying,
  "sync_limit" int8 NOT NULL DEFAULT 0,
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."job_schedule" OWNER TO "postgres";
COMMENT ON COLUMN "public"."job_schedule"."id" IS '自增主键';
COMMENT ON COLUMN "public"."job_schedule"."job_code" IS '任务编码（唯一）';
COMMENT ON COLUMN "public"."job_schedule"."cron_expr" IS 'Cron 表达式';
COMMENT ON COLUMN "public"."job_schedule"."enabled" IS '任务开关';
COMMENT ON COLUMN "public"."job_schedule"."max_concurrency" IS '并发上限';
COMMENT ON COLUMN "public"."job_schedule"."batch_size" IS '批量提交大小';
COMMENT ON COLUMN "public"."job_schedule"."http_timeout_sec" IS 'HTTP 超时（秒）';
COMMENT ON COLUMN "public"."job_schedule"."params" IS '自定义业务参数（JSON），如：{"syncHotelDetail":true,"syncHotelName":true}';
COMMENT ON COLUMN "public"."job_schedule"."sync_mode" IS '同步范围：FULL=全量；LIMIT=仅同步指定条数';
COMMENT ON COLUMN "public"."job_schedule"."sync_limit" IS '当 sync_mode=LIMIT 时的最大同步条数（0表示不限制）';
COMMENT ON COLUMN "public"."job_schedule"."remark" IS '备注';
COMMENT ON COLUMN "public"."job_schedule"."updated_at" IS '更新时间';
COMMENT ON TABLE "public"."job_schedule" IS '任务调度配置（DB驱动Cron），含业务参数与同步范围';

-- ----------------------------
-- Records of job_schedule
-- ----------------------------
BEGIN;
INSERT INTO "public"."job_schedule" ("id", "job_code", "cron_expr", "enabled", "max_concurrency", "batch_size", "http_timeout_sec", "params", "sync_mode", "sync_limit", "remark", "updated_at") VALUES (1, 'HOTEL_FULL_SYNC_ALL', '0 0 */2 * * ?', 't', 50, 1000, 60, '{"batchSize": 1000, "retryTimes": 3, "concurrency": 50, "retryDelayMs": 3000, "retryJitterMs": 2000, "httpTimeoutSec": 60, "maxConcurrency": 50, "hotelIdsBatchSize": 10000, "retryBaseDelayMs429": 1000, "hotelDetailBatchSize": 20}', 'FULL', 0, '酒店全量同步（按 maxHotelId 遍历）', '2025-10-29 13:38:04.08516+08');
INSERT INTO "public"."job_schedule" ("id", "job_code", "cron_expr", "enabled", "max_concurrency", "batch_size", "http_timeout_sec", "params", "sync_mode", "sync_limit", "remark", "updated_at") VALUES (2, 'HOTEL_RETRY_BY_SYNC_LOG', '0 0 0 1 1 ? 2099', 'f', 50, 1000, 60, '{"retry": {"multiplier": 2, "maxAttempts": 3, "initialBackoffMs": 1000}, "maxPages": 100, "batchSize": 1000, "syncLogId": 0, "concurrency": 20, "httpTimeoutSec": 60, "maxConcurrency": 20, "hotelIdsBatchSize": 10000, "hotelDetailBatchSize": 20}', 'LIMIT', 0, '失败明细补偿：按 sync_log_id 重放', '2025-10-29 13:38:04.095154+08');
COMMIT;

-- ----------------------------
-- Table structure for search_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."search_logs";
CREATE TABLE "public"."search_logs" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "query" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "tag_source" varchar(32) COLLATE "pg_catalog"."default",
  "result_count" int4,
  "clicked_hotel_id" int8,
  "click_position" int4,
  "duration_ms" int8,
  "user_id" int8,
  "user_ip" varchar(64) COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
)
;
ALTER TABLE "public"."search_logs" OWNER TO "postgres";
COMMENT ON COLUMN "public"."search_logs"."id" IS '自增主键';
COMMENT ON COLUMN "public"."search_logs"."query" IS '用户查询词';
COMMENT ON COLUMN "public"."search_logs"."tag_source" IS '业务域（CN/INTL/HMT）';
COMMENT ON COLUMN "public"."search_logs"."result_count" IS '搜索结果数量';
COMMENT ON COLUMN "public"."search_logs"."clicked_hotel_id" IS '点击的酒店ID';
COMMENT ON COLUMN "public"."search_logs"."click_position" IS '点击位置（排名）';
COMMENT ON COLUMN "public"."search_logs"."duration_ms" IS '查询耗时（毫秒）';
COMMENT ON COLUMN "public"."search_logs"."user_id" IS '用户ID（可选）';
COMMENT ON COLUMN "public"."search_logs"."user_ip" IS '用户IP地址';
COMMENT ON COLUMN "public"."search_logs"."created_at" IS '创建时间';
COMMENT ON TABLE "public"."search_logs" IS '搜索日志（用于搜索质量分析）';

-- ----------------------------
-- Records of search_logs
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for sync_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."sync_log";
CREATE TABLE "public"."sync_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "job_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "trace_id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "started_at" timestamptz(6) NOT NULL,
  "finished_at" timestamptz(6),
  "cost_seconds" int4,
  "total_ids" int8 DEFAULT 0,
  "total_details" int8 DEFAULT 0,
  "success_count" int8 DEFAULT 0,
  "fail_count" int8 DEFAULT 0,
  "status" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'RUNNING'::character varying,
  "message" text COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."sync_log" OWNER TO "postgres";
COMMENT ON COLUMN "public"."sync_log"."id" IS '自增主键';
COMMENT ON COLUMN "public"."sync_log"."job_code" IS '任务编码';
COMMENT ON COLUMN "public"."sync_log"."trace_id" IS '运行追踪ID（与 api_request_log 关联）';
COMMENT ON COLUMN "public"."sync_log"."started_at" IS '开始时间';
COMMENT ON COLUMN "public"."sync_log"."finished_at" IS '结束时间';
COMMENT ON COLUMN "public"."sync_log"."cost_seconds" IS '总耗时（秒）';
COMMENT ON COLUMN "public"."sync_log"."total_ids" IS '本次运行期间拉取到的酒店ID数量';
COMMENT ON COLUMN "public"."sync_log"."total_details" IS '成功解析并落地的酒店详情记录数';
COMMENT ON COLUMN "public"."sync_log"."success_count" IS '成功计数';
COMMENT ON COLUMN "public"."sync_log"."fail_count" IS '失败计数';
COMMENT ON COLUMN "public"."sync_log"."status" IS '运行状态（RUNNING/SUCCESS/FAILED/PARTIAL）';
COMMENT ON COLUMN "public"."sync_log"."message" IS '附加信息/备注';
COMMENT ON TABLE "public"."sync_log" IS '同步日志汇总（全局计数器）';

-- ----------------------------
-- Records of sync_log
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for sync_log_detail
-- ----------------------------
DROP TABLE IF EXISTS "public"."sync_log_detail";
CREATE TABLE "public"."sync_log_detail" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "sync_log_id" int8 NOT NULL,
  "hotel_id" int8,
  "stage" varchar(32) COLLATE "pg_catalog"."default",
  "error_code" varchar(64) COLLATE "pg_catalog"."default",
  "error_message" text COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) DEFAULT now()
)
;
ALTER TABLE "public"."sync_log_detail" OWNER TO "postgres";
COMMENT ON COLUMN "public"."sync_log_detail"."id" IS '自增主键';
COMMENT ON COLUMN "public"."sync_log_detail"."sync_log_id" IS '关联的同步日志ID';
COMMENT ON COLUMN "public"."sync_log_detail"."hotel_id" IS '酒店ID（可为空）';
COMMENT ON COLUMN "public"."sync_log_detail"."stage" IS '阶段（IDS_FETCH/DETAIL_FETCH/TRANSFORM/SINK/INDEX_*）';
COMMENT ON COLUMN "public"."sync_log_detail"."error_code" IS '错误码';
COMMENT ON COLUMN "public"."sync_log_detail"."error_message" IS '错误信息';
COMMENT ON COLUMN "public"."sync_log_detail"."created_at" IS '记录时间';
COMMENT ON TABLE "public"."sync_log_detail" IS '同步失败明细（支持按 sync_log_id 重跑补偿）';

-- ----------------------------
-- Records of sync_log_detail
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Auto increment value for api_request_log
-- ----------------------------
SELECT setval('"public"."api_request_log_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table api_request_log
-- ----------------------------
CREATE INDEX "idx_api_log_job" ON "public"."api_request_log" USING btree (
  "job_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_status" ON "public"."api_request_log" USING btree (
  "response_status" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_time" ON "public"."api_request_log" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_api_log_trace" ON "public"."api_request_log" USING btree (
  "trace_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table api_request_log
-- ----------------------------
ALTER TABLE "public"."api_request_log" ADD CONSTRAINT "api_request_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table hotel_poi
-- ----------------------------
ALTER TABLE "public"."hotel_poi" ADD CONSTRAINT "hotel_poi_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table hotels
-- ----------------------------
CREATE INDEX "idx_hotels_brand" ON "public"."hotels" USING btree (
  "hotel_brand_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "hotel_brand_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_city" ON "public"."hotels" USING btree (
  "city_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "city_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_continent" ON "public"."hotels" USING btree (
  "continent_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "continent_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_country" ON "public"."hotels" USING btree (
  "country_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "country_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "country_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_hotel_group" ON "public"."hotels" USING btree (
  "hotel_group_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "hotel_group_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_hotel_id" ON "public"."hotels" USING btree (
  "hotel_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_region" ON "public"."hotels" USING btree (
  "region_cn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "region_en" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_hotels_tag_source" ON "public"."hotels" USING btree (
  "tag_source" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table hotels
-- ----------------------------
ALTER TABLE "public"."hotels" ADD CONSTRAINT "uk_hotels_source_hotel" UNIQUE ("source", "hotel_id");

-- ----------------------------
-- Primary Key structure for table hotels
-- ----------------------------
ALTER TABLE "public"."hotels" ADD CONSTRAINT "hotels_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for job_runtime_state
-- ----------------------------
SELECT setval('"public"."job_runtime_state_id_seq1"', 1, false);

-- ----------------------------
-- Uniques structure for table job_runtime_state
-- ----------------------------
ALTER TABLE "public"."job_runtime_state" ADD CONSTRAINT "job_runtime_state_job_code_key" UNIQUE ("job_code");

-- ----------------------------
-- Primary Key structure for table job_runtime_state
-- ----------------------------
ALTER TABLE "public"."job_runtime_state" ADD CONSTRAINT "job_runtime_state_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for job_schedule
-- ----------------------------
SELECT setval('"public"."job_schedule_id_seq"', 2, true);

-- ----------------------------
-- Indexes structure for table job_schedule
-- ----------------------------
CREATE INDEX "idx_job_schedule_enabled" ON "public"."job_schedule" USING btree (
  "enabled" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table job_schedule
-- ----------------------------
ALTER TABLE "public"."job_schedule" ADD CONSTRAINT "job_schedule_job_code_key" UNIQUE ("job_code");

-- ----------------------------
-- Primary Key structure for table job_schedule
-- ----------------------------
ALTER TABLE "public"."job_schedule" ADD CONSTRAINT "job_schedule_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for search_logs
-- ----------------------------
SELECT setval('"public"."search_logs_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table search_logs
-- ----------------------------
CREATE INDEX "idx_search_logs_created_at" ON "public"."search_logs" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_search_logs_query" ON "public"."search_logs" USING btree (
  "query" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_search_logs_result_count" ON "public"."search_logs" USING btree (
  "result_count" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "idx_search_logs_tag_source" ON "public"."search_logs" USING btree (
  "tag_source" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table search_logs
-- ----------------------------
ALTER TABLE "public"."search_logs" ADD CONSTRAINT "search_logs_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for sync_log
-- ----------------------------
SELECT setval('"public"."sync_log_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table sync_log
-- ----------------------------
CREATE INDEX "idx_sync_log_job_code" ON "public"."sync_log" USING btree (
  "job_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_started_at" ON "public"."sync_log" USING btree (
  "started_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_status" ON "public"."sync_log" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table sync_log
-- ----------------------------
ALTER TABLE "public"."sync_log" ADD CONSTRAINT "sync_log_job_code_trace_id_key" UNIQUE ("job_code", "trace_id");

-- ----------------------------
-- Primary Key structure for table sync_log
-- ----------------------------
ALTER TABLE "public"."sync_log" ADD CONSTRAINT "sync_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for sync_log_detail
-- ----------------------------
SELECT setval('"public"."sync_log_detail_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table sync_log_detail
-- ----------------------------
CREATE INDEX "idx_sync_log_detail_hotel_id" ON "public"."sync_log_detail" USING btree (
  "hotel_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_detail_log_id" ON "public"."sync_log_detail" USING btree (
  "sync_log_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sync_log_detail_stage" ON "public"."sync_log_detail" USING btree (
  "stage" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table sync_log_detail
-- ----------------------------
ALTER TABLE "public"."sync_log_detail" ADD CONSTRAINT "sync_log_detail_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table sync_log_detail
-- ----------------------------
ALTER TABLE "public"."sync_log_detail" ADD CONSTRAINT "sync_log_detail_sync_log_id_fkey" FOREIGN KEY ("sync_log_id") REFERENCES "public"."sync_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
